// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMhVe954M4yst3TEiNzV9BpCloHCB4k0',
    appId: '1:251785480354:web:59ed2d50c9e51adb426ffb',
    messagingSenderId: '251785480354',
    projectId: 'ekart-2ddd2',
    authDomain: 'ekart-2ddd2.firebaseapp.com',
    storageBucket: 'ekart-2ddd2.appspot.com',
    measurementId: 'G-G2FWLLKNX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytFsfnN-1LFwwYPG_8Acs90PoHfZ9HDY',
    appId: '1:251785480354:android:bcfef5f053c2d9f0426ffb',
    messagingSenderId: '251785480354',
    projectId: 'ekart-2ddd2',
    storageBucket: 'ekart-2ddd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNA60eQM7zurwXPiP-mMs0dT8qUy4MV3c',
    appId: '1:251785480354:ios:95fca4a53adcb385426ffb',
    messagingSenderId: '251785480354',
    projectId: 'ekart-2ddd2',
    storageBucket: 'ekart-2ddd2.appspot.com',
    iosBundleId: 'com.example.ekart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNA60eQM7zurwXPiP-mMs0dT8qUy4MV3c',
    appId: '1:251785480354:ios:95fca4a53adcb385426ffb',
    messagingSenderId: '251785480354',
    projectId: 'ekart-2ddd2',
    storageBucket: 'ekart-2ddd2.appspot.com',
    iosBundleId: 'com.example.ekart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGMhVe954M4yst3TEiNzV9BpCloHCB4k0',
    appId: '1:251785480354:web:1af0be30a52182ba426ffb',
    messagingSenderId: '251785480354',
    projectId: 'ekart-2ddd2',
    authDomain: 'ekart-2ddd2.firebaseapp.com',
    storageBucket: 'ekart-2ddd2.appspot.com',
    measurementId: 'G-WMP7BEM20Y',
  );
}
